"""Human-readable reports for PromptBOM."""

import html
from typing import Any, Dict, List


def _summary_rows(bom: Dict[str, Any]) -> List[List[str]]:
    s = bom["summary"]
    return [
        ["Items", str(s.get("total", 0))],
        ["Mutable", str(s.get("mutable", 0))],
        ["Stale", str(s.get("stale", 0))],
        ["Secret findings", str(s.get("with_secret_findings", 0))],
        ["Possible conflicts", str(s.get("possible_conflicts", 0))],
        ["Root hash", str(s.get("root_hash", ""))],
    ]


def markdown_report(bom: Dict[str, Any]) -> str:
    lines: List[str] = [
        "# PromptBOM Report", "",
        "> SBOM for everything your AI was told.", "",
        "Generated by `%s` for **%s**." % (bom.get("tool", "promptbom"), bom.get("root", "project")),
        "", "## Summary", "", "| Metric | Value |", "|---|---:|",
    ]
    for key, value in _summary_rows(bom):
        lines.append("| %s | `%s` |" % (key, value))
    lines += ["", "## Ecosystems", "", "| Ecosystem | Items |", "|---|---:|"]
    for name, count in bom["summary"].get("by_ecosystem", {}).items():
        lines.append("| %s | %s |" % (name, count))
    lines += ["", "## Inventory", "", "| Authority | Kind | Ecosystem | Mutability | Age | SHA | Path |", "|---|---|---|---|---:|---|---|"]
    for item in bom.get("items", []):
        secret = " ⚠️" if item.get("secret_findings") else ""
        lines.append("| %s | %s | %s | %s | %sd | `%s` | `%s`%s |" % (
            item["authority"]["level"], item["kind"], item.get("ecosystem", "generic"), item["mutability"],
            item["freshness"]["age_days"], item["sha256"][:8], item["path"], secret))
    conflicts = bom.get("conflicts", [])
    lines += ["", "## Possible authority conflicts", ""]
    if not conflicts:
        lines.append("No heuristic conflicts detected.")
    else:
        lines.append("> These are heuristic signals, not proof of semantic contradiction.")
        lines.append("")
        for idx, conflict in enumerate(conflicts, 1):
            a, b = conflict["stronger"], conflict["weaker"]
            lines += [
                "### %d. Confidence %.0f%%" % (idx, conflict["confidence"] * 100),
                "- Stronger: `%s:%s` — %s" % (a["path"], a["line"], a["directive"]),
                "- Weaker: `%s:%s` — %s" % (b["path"], b["line"], b["directive"]),
                "",
            ]
    lines += ["## Security findings", ""]
    secret_items = [i for i in bom.get("items", []) if i.get("secret_findings")]
    if not secret_items:
        lines.append("No built-in secret-pattern findings.")
    else:
        for item in secret_items:
            for finding in item["secret_findings"]:
                lines.append("- `%s:%s` — `%s`" % (item["path"], finding["line"], finding["type"]))
    lines += ["", "---", "PromptBOM is local-first. Secret values are never written to the report.", ""]
    return "\n".join(lines)


def html_report(bom: Dict[str, Any]) -> str:
    def esc(v: Any) -> str:
        return html.escape(str(v))
    rows = []
    for item in bom.get("items", []):
        flag = "<span class='warn'>secret?</span>" if item.get("secret_findings") else ""
        rows.append("<tr><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%sd</td><td><code>%s</code></td><td><code>%s</code> %s</td></tr>" % (
            esc(item["authority"]["level"]), esc(item["kind"]), esc(item.get("ecosystem", "generic")),
            esc(item["mutability"]), esc(item["freshness"]["age_days"]), esc(item["sha256"][:8]), esc(item["path"]), flag))
    conflict_html = "<p>No heuristic conflicts detected.</p>"
    if bom.get("conflicts"):
        bits = ["<p class='muted'>Heuristic signals only; review manually.</p><ol>"]
        for c in bom["conflicts"]:
            a, b = c["stronger"], c["weaker"]
            bits.append("<li><strong>%.0f%%</strong> — <code>%s:%s</code> %s ↔ <code>%s:%s</code> %s</li>" % (
                c["confidence"] * 100, esc(a["path"]), esc(a["line"]), esc(a["directive"]),
                esc(b["path"]), esc(b["line"]), esc(b["directive"])))
        bits.append("</ol>")
        conflict_html = "".join(bits)
    s = bom["summary"]
    return """<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>PromptBOM Report</title><style>
:root{color-scheme:dark}body{margin:0;background:#070b16;color:#dce7ff;font:15px system-ui,-apple-system,Segoe UI,sans-serif}main{max-width:1180px;margin:auto;padding:42px 24px}h1{font-size:42px;margin-bottom:4px}.lead{color:#9eb1d1}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:12px;margin:28px 0}.card{background:#101a30;border:1px solid #283a62;border-radius:14px;padding:16px}.n{font-size:26px;font-weight:800;color:#75d4ff}table{width:100%%;border-collapse:collapse;background:#0c1427;border-radius:14px;overflow:hidden}th,td{padding:11px;border-bottom:1px solid #223251;text-align:left}th{color:#9fc9ff}code{color:#d3b6ff}.warn{color:#ffad6b}.muted{color:#92a4c2}a{color:#75d4ff}@media(max-width:720px){table{font-size:12px;display:block;overflow:auto}}
</style></head><body><main>
<h1>PromptBOM</h1><p class="lead">SBOM for everything your AI was told — %s</p>
<div class="cards"><div class="card">Items<div class="n">%s</div></div><div class="card">Mutable<div class="n">%s</div></div><div class="card">Stale<div class="n">%s</div></div><div class="card">Secrets?<div class="n">%s</div></div><div class="card">Conflicts?<div class="n">%s</div></div></div>
<h2>Inventory</h2><table><thead><tr><th>Authority</th><th>Kind</th><th>Ecosystem</th><th>Mutability</th><th>Age</th><th>SHA</th><th>Path</th></tr></thead><tbody>%s</tbody></table>
<h2>Possible authority conflicts</h2>%s
<p class="muted">Root hash: <code>%s</code><br>Generated by %s. Local-first; no secret values are embedded.</p>
</main></body></html>""" % (esc(bom.get("root", "project")), s.get("total", 0), s.get("mutable", 0), s.get("stale", 0), s.get("with_secret_findings", 0), s.get("possible_conflicts", 0), "".join(rows), conflict_html, esc(s.get("root_hash", "")), esc(bom.get("tool", "promptbom")))
